# ═══════════════════════════════════════════════════════════════════════════════
# GitHub Actions CI Pipeline — Seminarul 03
# Sisteme de Operare | ASE București - CSIE
# ═══════════════════════════════════════════════════════════════════════════════
# Fișier: .github/workflows/ci.yml (copiat din ci/github_actions.yml)
# ═══════════════════════════════════════════════════════════════════════════════

name: SEM03 CI Pipeline

on:
  push:
    branches: [main, master, develop]
    paths:
      - 'scripts/**'
      - 'formative/**'
      - 'tests/**'
      - 'Makefile'
      - 'requirements.txt'
  pull_request:
    branches: [main, master]
  workflow_dispatch:  # Permite rulare manuală

env:
  PYTHON_VERSION: '3.11'

jobs:
  # ═══════════════════════════════════════════════════════════════════════════════
  # JOB 1: LINTING
  # ═══════════════════════════════════════════════════════════════════════════════
  lint:
    name: Lint Code
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install shellcheck
        run: sudo apt-get update && sudo apt-get install -y shellcheck

      - name: Lint Bash scripts
        run: |
          echo "═══ Verificare Bash cu shellcheck ═══"
          shellcheck --shell=bash --severity=warning \
            scripts/bash/*.sh \
            scripts/demo/*.sh \
            teme/*.sh 2>/dev/null || true
          echo "✓ Shellcheck complet"

      - name: Check Bash syntax
        run: |
          echo "═══ Verificare sintaxă Bash ═══"
          for f in scripts/bash/*.sh scripts/demo/*.sh; do
            if [ -f "$f" ]; then
              bash -n "$f" || exit 1
            fi
          done
          echo "✓ Sintaxă Bash OK"

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install Python linters
        run: |
          pip install --upgrade pip
          pip install ruff

      - name: Lint Python with ruff
        run: |
          echo "═══ Verificare Python cu ruff ═══"
          ruff check scripts/python/*.py --output-format=github || true
          echo "✓ Ruff complet"

      - name: Check Python syntax
        run: |
          echo "═══ Verificare sintaxă Python ═══"
          for f in scripts/python/*.py; do
            if [ -f "$f" ]; then
              python -m py_compile "$f" || exit 1
            fi
          done
          echo "✓ Sintaxă Python OK"

  # ═══════════════════════════════════════════════════════════════════════════════
  # JOB 2: VALIDATE STRUCTURE
  # ═══════════════════════════════════════════════════════════════════════════════
  validate:
    name: Validate Structure
    runs-on: ubuntu-latest
    needs: lint
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install dependencies
        run: pip install pyyaml

      - name: Validate required files
        run: |
          echo "═══ Verificare fișiere obligatorii ═══"
          ERRORS=0
          
          # Verificare docs/
          for f in S03_00_ANALIZA_SI_PLAN_PEDAGOGIC.md \
                   S03_01_GHID_INSTRUCTOR.md \
                   S03_02_MATERIAL_PRINCIPAL.md \
                   S03_03_PEER_INSTRUCTION.md \
                   S03_04_PARSONS_PROBLEMS.md \
                   S03_05_LIVE_CODING_GUIDE.md \
                   lo_traceability.md; do
            if [ -f "docs/$f" ]; then
              echo "  ✓ docs/$f"
            else
              echo "  ✗ docs/$f LIPSEȘTE"
              ERRORS=$((ERRORS+1))
            fi
          done
          
          # Verificare root
          for f in README.md Makefile requirements.txt; do
            if [ -f "$f" ]; then
              echo "  ✓ $f"
            else
              echo "  ✗ $f LIPSEȘTE"
              ERRORS=$((ERRORS+1))
            fi
          done
          
          # Verificare formative/
          for f in quiz.yaml quiz_lms.json; do
            if [ -f "formative/$f" ]; then
              echo "  ✓ formative/$f"
            else
              echo "  ✗ formative/$f LIPSEȘTE"
              ERRORS=$((ERRORS+1))
            fi
          done
          
          if [ $ERRORS -gt 0 ]; then
            echo "═══ $ERRORS fișiere lipsă! ═══"
            exit 1
          fi
          echo "═══ Toate fișierele prezente ═══"

      - name: Validate YAML quiz
        run: |
          echo "═══ Validare quiz.yaml ═══"
          python -c "
          import yaml
          import sys
          
          with open('formative/quiz.yaml', 'r', encoding='utf-8') as f:
              quiz = yaml.safe_load(f)
          
          # Verificări de bază
          assert 'metadata' in quiz, 'Lipsește metadata'
          assert 'intrebari' in quiz, 'Lipsesc întrebările'
          
          questions = quiz['intrebari']
          print(f'  Întrebări găsite: {len(questions)}')
          
          # Verificare structură întrebări
          for i, q in enumerate(questions):
              assert 'id' in q, f'Întrebare {i}: lipsește id'
              assert 'text' in q, f'Întrebare {i}: lipsește text'
              assert 'optiuni' in q, f'Întrebare {i}: lipsesc opțiuni'
              assert 'corect' in q, f'Întrebare {i}: lipsește răspuns corect'
          
          print('✓ Quiz YAML valid și complet')
          "

      - name: Validate JSON quiz
        run: |
          echo "═══ Validare quiz_lms.json ═══"
          python -c "
          import json
          
          with open('formative/quiz_lms.json', 'r', encoding='utf-8') as f:
              quiz = json.load(f)
          
          assert 'questions' in quiz, 'Lipsesc întrebările'
          print(f'  Întrebări găsite: {len(quiz[\"questions\"])}')
          print('✓ Quiz JSON valid')
          "

  # ═══════════════════════════════════════════════════════════════════════════════
  # JOB 3: RUN TESTS
  # ═══════════════════════════════════════════════════════════════════════════════
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    needs: validate
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
          fi

      - name: Run test suite
        run: |
          echo "═══ Rulare teste ═══"
          if [ -f "teste/run_all_tests.sh" ]; then
            chmod +x teste/run_all_tests.sh
            bash teste/run_all_tests.sh
          else
            echo "Teste de bază (fără runner dedicat)..."
            # Verificare import-uri Python
            for f in scripts/python/*.py; do
              if [ -f "$f" ]; then
                python -c "import sys; sys.path.insert(0, '.'); exec(open('$f').read())" 2>/dev/null || true
              fi
            done
            echo "✓ Verificări de bază complete"
          fi

  # ═══════════════════════════════════════════════════════════════════════════════
  # JOB 4: CHECK AI PATTERNS (optional)
  # ═══════════════════════════════════════════════════════════════════════════════
  ai-check:
    name: Check AI Patterns
    runs-on: ubuntu-latest
    needs: lint
    continue-on-error: true  # Nu blochează pipeline-ul
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Check for AI signal words
        run: |
          echo "═══ Verificare cuvinte-semnal AI ═══"
          AI_WORDS="delve|leverage|comprehensive|robust|seamless|cutting-edge|foster|cultivate|harness|pivotal|paramount|utilize|facilitate|streamline|embark|journey|landscape|ecosystem"
          
          COUNT=$(grep -riE "$AI_WORDS" --include="*.md" --include="*.sh" . 2>/dev/null | wc -l || echo "0")
          
          if [ "$COUNT" -gt 10 ]; then
            echo "⚠️ Avertisment: $COUNT instanțe de cuvinte AI detectate"
            grep -riE "$AI_WORDS" --include="*.md" . 2>/dev/null | head -20 || true
          else
            echo "✓ Număr acceptabil de cuvinte AI: $COUNT"
          fi

      - name: Check naming consistency
        run: |
          echo "═══ Verificare consistență naming ═══"
          ISSUES=$(grep -rE "Seminar 5-6|sem56|SEM05-06" --include="*.md" --include="*.sh" . 2>/dev/null | wc -l || echo "0")
          
          if [ "$ISSUES" -gt 0 ]; then
            echo "⚠️ Avertisment: $ISSUES referințe inconsistente la numerotare"
            grep -rE "Seminar 5-6|sem56" --include="*.md" . 2>/dev/null | head -10 || true
          else
            echo "✓ Naming consistent"
          fi
