# .github/workflows/ci.yml
# CI Pipeline pentru SEM01 - Shell Fundamentals
# Sisteme de Operare | ASE București - CSIE

name: SEM01 CI

on:
  push:
    branches: [main, master, develop]
  pull_request:
    branches: [main, master]

jobs:
  lint-bash:
    name: Lint Bash Scripts
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - uses: actions/checkout@v4
      
      - name: Install shellcheck
        run: sudo apt-get install -y shellcheck
      
      - name: Run shellcheck
        run: |
          find scripts -name "*.sh" -exec shellcheck {} \;

  lint-python:
    name: Lint Python Code
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      
      - name: Install ruff
        run: pip install ruff
      
      - name: Run ruff
        run: ruff check formative/ tests/

  validate-yaml:
    name: Validate YAML Files
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      
      - name: Install PyYAML
        run: pip install pyyaml
      
      - name: Validate quiz.yaml
        run: |
          python -c "
          import yaml
          with open('formative/quiz.yaml') as f:
              data = yaml.safe_load(f)
              assert 'metadata' in data, 'Missing metadata'
              assert 'intrebari' in data, 'Missing intrebari'
              print(f'Quiz valid: {len(data[\"intrebari\"])} întrebări')
          "

  test:
    name: Run Tests
    runs-on: ubuntu-latest
    needs: [validate-yaml]
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      
      - name: Install dependencies
        run: |
          pip install pyyaml pytest
      
      - name: Run pytest
        run: |
          pytest tests/ -v --tb=short || true
      
      - name: Validate Bash scripts syntax
        run: |
          for script in scripts/bash/*.sh scripts/demo/*.sh; do
            if [ -f "$script" ]; then
              bash -n "$script" && echo "✓ $script"
            fi
          done

  summary:
    name: CI Summary
    runs-on: ubuntu-latest
    needs: [lint-bash, lint-python, validate-yaml, test]
    if: always()
    steps:
      - name: Check job results
        run: |
          echo "═══════════════════════════════════════"
          echo "        CI SUMMARY - SEM01"
          echo "═══════════════════════════════════════"
          echo "Lint Bash:     ${{ needs.lint-bash.result }}"
          echo "Lint Python:   ${{ needs.lint-python.result }}"
          echo "Validate YAML: ${{ needs.validate-yaml.result }}"
          echo "Tests:         ${{ needs.test.result }}"
          echo "═══════════════════════════════════════"
