# ═══════════════════════════════════════════════════════════════════════════════
# GitHub Actions CI - Seminarul 02 SO
# ═══════════════════════════════════════════════════════════════════════════════
#
# Pipeline de validare automată pentru materialele seminarului.
# Rulează la fiecare push și pull request.
#
# Jobs:
#   1. lint-bash    - Verificare shellcheck pentru scripturi Bash
#   2. lint-python  - Verificare sintaxă și stil Python
#   3. test         - Rulare teste automate
#   4. validate     - Verificare structură pachet
#
# ═══════════════════════════════════════════════════════════════════════════════

name: SEM02 Validation Pipeline

on:
  push:
    branches: [main, develop]
    paths:
      - 'SEM02/**'
      - '.github/workflows/**'
  pull_request:
    branches: [main]
    paths:
      - 'SEM02/**'
  workflow_dispatch:  # Permite rulare manuală

env:
  SEMINAR_DIR: SEM02

jobs:
  # ═══════════════════════════════════════════════════════════════════════════
  # JOB 1: Lint Bash Scripts
  # ═══════════════════════════════════════════════════════════════════════════
  
  lint-bash:
    name: Lint Bash Scripts
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Install shellcheck
        run: sudo apt-get install -y shellcheck
      
      - name: Run shellcheck on bash scripts
        run: |
          echo "=== Verificare scripts/bash/ ==="
          shellcheck --severity=warning ${{ env.SEMINAR_DIR }}/scripts/bash/*.sh || true
          
          echo "=== Verificare scripts/demo/ ==="
          shellcheck --severity=warning ${{ env.SEMINAR_DIR }}/scripts/demo/*.sh || true
          
          echo "=== Verificare teme/*.sh ==="
          if ls ${{ env.SEMINAR_DIR }}/teme/*.sh 1> /dev/null 2>&1; then
            shellcheck --severity=warning ${{ env.SEMINAR_DIR }}/teme/*.sh || true
          fi
      
      - name: Check bash syntax
        run: |
          echo "=== Verificare sintaxă Bash ==="
          for script in ${{ env.SEMINAR_DIR }}/scripts/bash/*.sh ${{ env.SEMINAR_DIR }}/scripts/demo/*.sh; do
            echo "Checking: $script"
            bash -n "$script"
          done
          echo "✓ Toate scripturile au sintaxă validă"

  # ═══════════════════════════════════════════════════════════════════════════
  # JOB 2: Lint Python Scripts
  # ═══════════════════════════════════════════════════════════════════════════
  
  lint-python:
    name: Lint Python Scripts
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ruff pyyaml
          if [ -f ${{ env.SEMINAR_DIR }}/requirements.txt ]; then
            pip install -r ${{ env.SEMINAR_DIR }}/requirements.txt
          fi
      
      - name: Check Python syntax
        run: |
          echo "=== Verificare sintaxă Python ==="
          for pyfile in ${{ env.SEMINAR_DIR }}/scripts/python/*.py; do
            echo "Checking: $pyfile"
            python -m py_compile "$pyfile"
          done
          
          if [ -d "${{ env.SEMINAR_DIR }}/formative" ]; then
            for pyfile in ${{ env.SEMINAR_DIR }}/formative/*.py; do
              if [ -f "$pyfile" ]; then
                echo "Checking: $pyfile"
                python -m py_compile "$pyfile"
              fi
            done
          fi
          echo "✓ Toate scripturile Python au sintaxă validă"
      
      - name: Run ruff linter
        run: |
          echo "=== Rulare ruff ==="
          ruff check ${{ env.SEMINAR_DIR }}/scripts/python/ --ignore=E501 || true
          if [ -d "${{ env.SEMINAR_DIR }}/formative" ]; then
            ruff check ${{ env.SEMINAR_DIR }}/formative/ --ignore=E501 || true
          fi

  # ═══════════════════════════════════════════════════════════════════════════
  # JOB 3: Run Tests
  # ═══════════════════════════════════════════════════════════════════════════
  
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    needs: [lint-bash, lint-python]
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      
      - name: Install Python dependencies
        run: |
          pip install pyyaml
          if [ -f ${{ env.SEMINAR_DIR }}/requirements.txt ]; then
            pip install -r ${{ env.SEMINAR_DIR }}/requirements.txt
          fi
      
      - name: Run test suite
        run: |
          cd ${{ env.SEMINAR_DIR }}
          if [ -f "teste/run_all_tests.sh" ]; then
            echo "=== Rulare teste automate ==="
            bash teste/run_all_tests.sh
          else
            echo "=== Verificare de bază ==="
            # Verifică că scripturile principale se pot importa/rula
            for script in scripts/bash/*.sh; do
              bash -n "$script"
            done
            echo "✓ Teste de bază trecute"
          fi
      
      - name: Validate quiz YAML
        run: |
          cd ${{ env.SEMINAR_DIR }}
          if [ -f "formative/quiz.yaml" ]; then
            echo "=== Validare quiz.yaml ==="
            python3 -c "import yaml; yaml.safe_load(open('formative/quiz.yaml'))"
            echo "✓ quiz.yaml valid"
          fi
      
      - name: Validate quiz JSON
        run: |
          cd ${{ env.SEMINAR_DIR }}
          if [ -f "formative/quiz_lms.json" ]; then
            echo "=== Validare quiz_lms.json ==="
            python3 -c "import json; json.load(open('formative/quiz_lms.json'))"
            echo "✓ quiz_lms.json valid"
          fi

  # ═══════════════════════════════════════════════════════════════════════════
  # JOB 4: Validate Structure
  # ═══════════════════════════════════════════════════════════════════════════
  
  validate:
    name: Validate Package Structure
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Check required files
        run: |
          cd ${{ env.SEMINAR_DIR }}
          echo "=== Verificare fișiere obligatorii ==="
          
          MISSING=0
          
          # Lista fișierelor obligatorii
          REQUIRED_FILES=(
            "README.md"
            "docs/S02_00_ANALIZA_SI_PLAN_PEDAGOGIC.md"
            "docs/S02_01_GHID_INSTRUCTOR.md"
            "docs/S02_02_MATERIAL_PRINCIPAL.md"
            "docs/S02_03_PEER_INSTRUCTION.md"
            "docs/S02_04_PARSONS_PROBLEMS.md"
            "docs/S02_05_LIVE_CODING_GUIDE.md"
            "docs/S02_06_EXERCITII_SPRINT.md"
            "docs/S02_07_LLM_AWARE_EXERCISES.md"
            "docs/S02_08_DEMO_SPECTACULOASE.md"
            "docs/S02_09_CHEAT_SHEET_VIZUAL.md"
            "docs/S02_10_AUTOEVALUARE_REFLEXIE.md"
            "scripts/bash/S02_01_setup_seminar.sh"
            "scripts/bash/S02_02_quiz_interactiv.sh"
            "scripts/bash/S02_03_validator.sh"
            "scripts/python/S02_01_autograder.py"
            "scripts/python/S02_02_quiz_generator.py"
            "scripts/python/S02_03_report_generator.py"
          )
          
          for f in "${REQUIRED_FILES[@]}"; do
            if [ -f "$f" ]; then
              echo "✓ $f"
            else
              echo "✗ $f (LIPSĂ)"
              MISSING=$((MISSING + 1))
            fi
          done
          
          echo ""
          echo "=== Verificare fișiere opționale (CI/CD) ==="
          
          OPTIONAL_FILES=(
            "formative/quiz.yaml"
            "formative/quiz_lms.json"
            "formative/quiz_runner.py"
            "docs/lo_traceability.md"
            "Makefile"
            "requirements.txt"
            "ci/github_actions.yml"
            "ci/linting.toml"
          )
          
          for f in "${OPTIONAL_FILES[@]}"; do
            if [ -f "$f" ]; then
              echo "✓ $f"
            else
              echo "○ $f (opțional)"
            fi
          done
          
          echo ""
          if [ $MISSING -eq 0 ]; then
            echo "═══ Structură validă! ═══"
          else
            echo "═══ $MISSING fișiere obligatorii lipsă! ═══"
            exit 1
          fi
      
      - name: Count content
        run: |
          cd ${{ env.SEMINAR_DIR }}
          echo "=== Statistici conținut ==="
          echo "Fișiere Markdown: $(find . -name '*.md' | wc -l)"
          echo "Scripturi Bash: $(find . -name '*.sh' | wc -l)"
          echo "Scripturi Python: $(find . -name '*.py' | wc -l)"
          echo "Fișiere HTML: $(find . -name '*.html' | wc -l)"
          echo ""
          echo "Linii total Markdown: $(find . -name '*.md' -exec cat {} + | wc -l)"
          echo "Linii total Bash: $(find . -name '*.sh' -exec cat {} + | wc -l)"
          echo "Linii total Python: $(find . -name '*.py' -exec cat {} + | wc -l)"

# ═══════════════════════════════════════════════════════════════════════════════
# FIN
# ═══════════════════════════════════════════════════════════════════════════════
