@startuml
title Linux Namespaces
rectangle "PID" as pid
rectangle "NET" as net
rectangle "MNT" as mnt
rectangle "UTS" as uts
rectangle "IPC" as ipc
rectangle "USER" as user
rectangle "CGROUP" as cgrp
rectangle "Container" as c
c --> pid
c --> net
c --> mnt
c --> uts
c --> ipc
c --> user
c --> cgrp
@enduml